# MCP Server Configuration Template
server:
  name: "my-mcp-server"
  version: "1.0.0"
  description: "Custom MCP Server"
  
  # Transport configuration
  transport:
    # For STDIO transport (local use)
    stdio:
      enabled: true
      
    # For SSE transport (remote use)  
    sse:
      enabled: false
      host: "127.0.0.1"
      port: 8080
      cors_origins: ["*"]
      
  # Logging configuration
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    file: "logs/server.log"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
  # Security settings
  security:
    enable_auth: false
    api_key: ""
    allowed_origins: []
    rate_limiting:
      enabled: false
      requests_per_minute: 60
      
# Tools configuration
tools:
  # Built-in tools
  builtin:
    echo: true
    calculate: true
    get_time: true
    
  # Custom tools directory
  custom_tools_dir: "servers/tools"
  
  # Tool-specific settings
  settings:
    file_operations:
      allowed_directories: ["./data", "./tmp"]
      max_file_size: "10MB"
    
# Resources configuration  
resources:
  enabled: true
  max_size: "1MB"
  cache_ttl: 300  # seconds
  
# Database settings (if applicable)
database:
  type: "sqlite"  # sqlite, postgresql, mysql
  url: "sqlite:///data/app.db"
  pool_size: 10
  
# Environment-specific overrides
environments:
  development:
    logging:
      level: "DEBUG"
    security:
      enable_auth: false
      
  production:
    logging:
      level: "WARNING"
    security:
      enable_auth: true
      rate_limiting:
        enabled: true
        requests_per_minute: 100